name: interval_tree
version: 0.0.1
description: >-
  A Dart port minimal C++ interval tree implementation by Erik Garrison:
  https://github.com/ekg/intervaltree
homepage: https://pub.dev/packages/interval_tree
repository: https://github.com/jpnurmi/interval_tree
issue_tracker: https://github.com/jpnurmi/interval_tree/issues

environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  quiver: ^2.1.3
dev_dependencies:
  test: ^1.14.2
  test_coverage: ^0.4.1
