name: analyze

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  package-analysis:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: axel-op/dart-package-analyzer@stable
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
